#### this for companies
POST http://localhost:3000/companies HTTP/1.1
content-type: application/json


  {
  "companyName": "Google",
  "password": "John",
  "email": "John@gmail.com",
  "about": "Software Engineer with 5 years experience"
  }

####
POST  http://localhost:3000/companies/addJobs/homeDepoty
content-type: application/json
    
{
  "jobRole": "Front end developer",
  "experience": "4",
  "skills":"Back end developer",
  "jobDescription": "Working hard",
  "jobType": "Full time"
}

####

POST  http://localhost:3000/seekers/applyjobs/bekele/keforce
content-type: application/json
    
{
  "jobRole": "Back end developer",
  "experience": "5",
  "skills":"Full stack developer",
  "jobDescription": "Software Engineering position",
  "jobType": "Full time"
}

###
PATCH http://localhost:3000/companies/addSeekers/miu 
content-type: application/json

{
   "name": "Eyouel",
   "email": "Eyouel@gmail.com",
   "phone": "0911223344",
   "location": "Iowa"
}

####
POST http://localhost:3000/companies/login HTTP/1.1
content-type: application/json

{
  "companyName": "Amazon",
  "password": "PE1234"
}

#### this for Seekers

POST http://localhost:3000/seekers HTTP/1.1
content-type: application/json

  {
  "name": "Doe",
  "password":"1234" ,
  "email": "John@gmail.com",
  "phone":"0888888888",
  "experience": "2",
  "location": "FairFeild",
  "gender": "Male",
  "interests":"Front End"
  }
  
###
POST http://localhost:3000/seekers/login HTTP/1.1
content-type: application/json

{
  "name": "White",
  "password": "white1234"
}

#### 

GET http://localhost:3000/seekers/getJobs

################################
GET http://localhost:3000/seekers
